name: ubuzima_native
description: Ubuzima+ mobile application.
publish_to: none
version: 3.2.0-rc.5+32005

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/branding/ubuzima-logo.png
