#!/usr/bin/env bash
set -euo pipefail

echo "== Controlled package generation execution checksum target quarantine ledger source identity =="
echo "Current branch: $(git branch --show-current)"
echo "Current commit: $(git rev-parse --short HEAD)"

echo "== Protected-file tracked source inspection =="
PROTECTED="$(git ls-files | grep -E '(^|/)(\.env$|\.env\.[^.]+$|database\.sqlite$|vendor/|node_modules/|public_html/|backup|backups|\.pem$|\.key$|id_rsa|id_ed25519)' | grep -v -E '(^|/)\.env\.example$' || true)"
if [ -n "$PROTECTED" ]; then
  echo "$PROTECTED"
  echo "Protected tracked files found."
  exit 1
fi
echo "No protected tracked files found."

LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_CHECKSUM_TARGET_QUARANTINE_LEDGER.md"
EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_CHECKSUM_TARGET_QUARANTINE_EXCEPTION_LOG.md"

ARCHIVE_TARGET_QUARANTINE_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_ARCHIVE_TARGET_QUARANTINE_LEDGER.md"
ARCHIVE_TARGET_QUARANTINE_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_ARCHIVE_TARGET_QUARANTINE_EXCEPTION_LOG.md"

PACKAGE_BUILD_QUARANTINE_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_PACKAGE_BUILD_COMMAND_QUARANTINE_LEDGER.md"
PACKAGE_BUILD_QUARANTINE_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_PACKAGE_BUILD_COMMAND_QUARANTINE_EXCEPTION_LOG.md"

FINAL_GO_NO_GO_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_FINAL_GO_NO_GO_HOLD_LEDGER.md"
FINAL_GO_NO_GO_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_FINAL_GO_NO_GO_HOLD_EXCEPTION_LOG.md"

FINAL_AUTH_EVIDENCE_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_FINAL_AUTHORIZATION_EVIDENCE_LEDGER.md"
FINAL_AUTH_EVIDENCE_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_FINAL_AUTHORIZATION_EVIDENCE_EXCEPTION_LOG.md"

OWNER_LOCK_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_OWNER_AUTHORIZATION_LOCK_LEDGER.md"
OWNER_LOCK_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_OWNER_AUTHORIZATION_LOCK_EXCEPTION_LOG.md"

RELEASE_AUTH_HOLD_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_RELEASE_AUTHORIZATION_HOLD_LEDGER.md"
RELEASE_AUTH_HOLD_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_RELEASE_AUTHORIZATION_HOLD_EXCEPTION_LOG.md"

OPERATOR_RELEASE_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_OPERATOR_RELEASE_APPROVAL_LEDGER.md"
OPERATOR_RELEASE_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_OPERATOR_RELEASE_APPROVAL_EXCEPTION_LOG.md"

FINAL_RELEASE_GATE_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_FINAL_RELEASE_GATE_LEDGER.md"
FINAL_RELEASE_GATE_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_FINAL_RELEASE_GATE_EXCEPTION_LOG.md"

READINESS_SIGNOFF_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_READINESS_SIGNOFF_LEDGER.md"
READINESS_SIGNOFF_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_READINESS_SIGNOFF_EXCEPTION_LOG.md"

RELEASE_READINESS_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_RELEASE_READINESS_LEDGER.md"
RELEASE_READINESS_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_RELEASE_READINESS_EXCEPTION_LOG.md"

APPROVAL_CLOSURE_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_APPROVAL_CLOSURE_LEDGER.md"
APPROVAL_CLOSURE_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_APPROVAL_CLOSURE_EXCEPTION_LOG.md"

DECISION_HOLD_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_DECISION_HOLD_LEDGER.md"
DECISION_HOLD_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_DECISION_EXCEPTION_LOG.md"

FINAL_AUTH_PACKET="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_FINAL_EXECUTION_AUTHORIZATION_PACKET.md"
FINAL_AUTH_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_FINAL_EXECUTION_AUTHORIZATION_EXCEPTION_LOG.md"

COMMAND_HOLD_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_COMMAND_RELEASE_HOLD_LEDGER.md"
COMMAND_HOLD_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_COMMAND_RELEASE_HOLD_EXCEPTION_LOG.md"

PREFLIGHT_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_EVIDENCE_PREFLIGHT_LEDGER.md"
PREFLIGHT_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_PREFLIGHT_EXCEPTION_LOG.md"

AUTH_RELEASE_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_AUTHORIZATION_RELEASE_LEDGER.md"
AUTH_RELEASE_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_RELEASE_EXCEPTION_LOG.md"

READINESS_LOCK="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_PACKAGE_GENERATION_READINESS_LOCK_LEDGER.md"
READINESS_UNLOCK_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_PACKAGE_GENERATION_READINESS_UNLOCK_EXCEPTION_LOG.md"

echo "== Required Phase 18.3 documents =="
for required in   "$LEDGER"   "$EXCEPTION_LOG"   "$ARCHIVE_TARGET_QUARANTINE_LEDGER"   "$ARCHIVE_TARGET_QUARANTINE_EXCEPTION_LOG"   "$PACKAGE_BUILD_QUARANTINE_LEDGER"   "$PACKAGE_BUILD_QUARANTINE_EXCEPTION_LOG"   "$FINAL_GO_NO_GO_LEDGER"   "$FINAL_GO_NO_GO_EXCEPTION_LOG"   "$FINAL_AUTH_EVIDENCE_LEDGER"   "$FINAL_AUTH_EVIDENCE_EXCEPTION_LOG"   "$OWNER_LOCK_LEDGER"   "$OWNER_LOCK_EXCEPTION_LOG"   "$RELEASE_AUTH_HOLD_LEDGER"   "$RELEASE_AUTH_HOLD_EXCEPTION_LOG"   "$OPERATOR_RELEASE_LEDGER"   "$OPERATOR_RELEASE_EXCEPTION_LOG"   "$FINAL_RELEASE_GATE_LEDGER"   "$FINAL_RELEASE_GATE_EXCEPTION_LOG"   "$READINESS_SIGNOFF_LEDGER"   "$READINESS_SIGNOFF_EXCEPTION_LOG"   "$RELEASE_READINESS_LEDGER"   "$RELEASE_READINESS_EXCEPTION_LOG"   "$APPROVAL_CLOSURE_LEDGER"   "$APPROVAL_CLOSURE_EXCEPTION_LOG"   "$DECISION_HOLD_LEDGER"   "$DECISION_HOLD_EXCEPTION_LOG"   "$FINAL_AUTH_PACKET"   "$FINAL_AUTH_EXCEPTION_LOG"   "$COMMAND_HOLD_LEDGER"   "$COMMAND_HOLD_EXCEPTION_LOG"   "$PREFLIGHT_LEDGER"   "$PREFLIGHT_EXCEPTION_LOG"   "$AUTH_RELEASE_LEDGER"   "$AUTH_RELEASE_EXCEPTION_LOG"   "$READINESS_LOCK"   "$READINESS_UNLOCK_LOG"
do
  if [ ! -f "$required" ]; then
    echo "Missing required document: $required"
    exit 1
  fi
  echo "Found: $required"
done

grep -q "No checksum target path was released" "$LEDGER"
grep -q "No checksum target path was executed" "$LEDGER"
grep -q "No checksum was generated" "$LEDGER"
grep -q "No archive target path was released" "$LEDGER"
grep -q "No archive target path was executed" "$LEDGER"
grep -q "No package archive was created" "$LEDGER"
grep -q "No package-build command was released" "$LEDGER"
grep -q "No package-build command was executed" "$LEDGER"
grep -q "No package generation was executed" "$LEDGER"
grep -q "No cPanel execution occurred" "$LEDGER"
grep -q "No live deployment occurred" "$LEDGER"
grep -q "No data mutation occurred" "$LEDGER"
grep -q "The system remains in controlled checksum target quarantine hold status" "$LEDGER"

npm --prefix web/admin-dashboard run build

echo "PharmaCo360 operations controlled package generation execution checksum target quarantine ledger check passed."
