#!/usr/bin/env bash
set -euo pipefail

echo "== Controlled package generation execution final release gate ledger source identity =="
echo "Current branch: $(git branch --show-current)"
echo "Current commit: $(git rev-parse --short HEAD)"

echo "== Protected-file tracked source inspection =="
PROTECTED="$(git ls-files | grep -E '(^|/)(\.env$|\.env\.[^.]+$|database\.sqlite$|vendor/|node_modules/|public_html/|backup|backups|\.pem$|\.key$|id_rsa|id_ed25519)' | grep -v -E '(^|/)\.env\.example$' || true)"
if [ -n "$PROTECTED" ]; then
  echo "$PROTECTED"
  echo "Protected tracked files found."
  exit 1
fi
echo "No protected tracked files found."

LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_FINAL_RELEASE_GATE_LEDGER.md"
EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_FINAL_RELEASE_GATE_EXCEPTION_LOG.md"
SIGNOFF_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_READINESS_SIGNOFF_LEDGER.md"
SIGNOFF_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_READINESS_SIGNOFF_EXCEPTION_LOG.md"
RELEASE_READINESS_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_RELEASE_READINESS_LEDGER.md"
RELEASE_READINESS_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_RELEASE_READINESS_EXCEPTION_LOG.md"
APPROVAL_CLOSURE_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_APPROVAL_CLOSURE_LEDGER.md"
APPROVAL_CLOSURE_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_APPROVAL_CLOSURE_EXCEPTION_LOG.md"
DECISION_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_DECISION_HOLD_LEDGER.md"
DECISION_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_DECISION_EXCEPTION_LOG.md"
AUTH_PACKET="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_FINAL_EXECUTION_AUTHORIZATION_PACKET.md"
AUTH_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_FINAL_EXECUTION_AUTHORIZATION_EXCEPTION_LOG.md"
COMMAND_HOLD_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_COMMAND_RELEASE_HOLD_LEDGER.md"
COMMAND_HOLD_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_COMMAND_RELEASE_HOLD_EXCEPTION_LOG.md"
PREFLIGHT_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_EVIDENCE_PREFLIGHT_LEDGER.md"
PREFLIGHT_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_EXECUTION_PREFLIGHT_EXCEPTION_LOG.md"
AUTH_RELEASE_LEDGER="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_AUTHORIZATION_RELEASE_LEDGER.md"
AUTH_RELEASE_EXCEPTION_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_CONTROLLED_PACKAGE_GENERATION_RELEASE_EXCEPTION_LOG.md"
READINESS_LOCK="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_PACKAGE_GENERATION_READINESS_LOCK_LEDGER.md"
READINESS_UNLOCK_LOG="docs/deployment/PHARMACO_OPERATIONS_COMMAND_CENTER_PACKAGE_GENERATION_READINESS_UNLOCK_EXCEPTION_LOG.md"

echo "== Required Phase 17.5 documents =="
for required in   "$LEDGER"   "$EXCEPTION_LOG"   "$SIGNOFF_LEDGER"   "$SIGNOFF_EXCEPTION_LOG"   "$RELEASE_READINESS_LEDGER"   "$RELEASE_READINESS_EXCEPTION_LOG"   "$APPROVAL_CLOSURE_LEDGER"   "$APPROVAL_CLOSURE_EXCEPTION_LOG"   "$DECISION_LEDGER"   "$DECISION_EXCEPTION_LOG"   "$AUTH_PACKET"   "$AUTH_EXCEPTION_LOG"   "$COMMAND_HOLD_LEDGER"   "$COMMAND_HOLD_EXCEPTION_LOG"   "$PREFLIGHT_LEDGER"   "$PREFLIGHT_EXCEPTION_LOG"   "$AUTH_RELEASE_LEDGER"   "$AUTH_RELEASE_EXCEPTION_LOG"   "$READINESS_LOCK"   "$READINESS_UNLOCK_LOG"
do
  if [ ! -f "$required" ]; then
    echo "Missing required document: $required"
    exit 1
  fi
  echo "Found: $required"
done

grep -q "No package archive was created" "$LEDGER"
grep -q "No package generation was executed" "$LEDGER"
grep -q "No cPanel execution occurred" "$LEDGER"
grep -q "No live deployment occurred" "$LEDGER"
grep -q "No data mutation occurred" "$LEDGER"
grep -q "The system remains in controlled release gate hold status" "$LEDGER"

npm --prefix web/admin-dashboard run build

echo "PharmaCo360 operations controlled package generation execution final release gate ledger check passed."
